server:
  port: 8082
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cafebillingapp
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    
logging:
  file:
    path: \CafeBilling\LOGS
    name: CafeEBillingLogs.log
 
